apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: f-kle-aiml-1234   # replace with the name of profile you want, this will be user's namespace name
spec:
  owner:
    kind: User
    name: f-kle-aiml-1234   # replace with the email of the user

  resourceQuotaSpec:    # resource quota can be set optionally
   hard:
     cpu: "9"
     memory: "33Gi"
     requests.nvidia.com/gpu: "1"
     requests.nvidia.com/mig-3g.40gb: "1"
     requests.nvidia.com/mig-2g.20gb: "1"
     requests.nvidia.com/mig-1g.10gb: "1"
     requests.storage: "50Gi"

