apiVersion: v1
kind: PersistentVolume
metadata:
  name: ln-f-giindia-support-12
spec:
  capacity:
    storage: 50Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  
  hostPath:
    path: /workspace/login_node_pv/ln-f-giindia-support-12  
