apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ln-f-giindia-support-12
  namespace: ln-f-giindia-support-12
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  
  storageClassName: manual 
