apiVersion: v1
kind: PersistentVolume
metadata:
  name: ln-s-jaincollege-cs-1234
spec:
  capacity:
    storage: 50Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  
  hostPath:
    path: /workspace/login_node_pv/ln-s-jaincollege-cs-1234  
