apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ln-s-jaincollege-cs-1234
  namespace: ln-s-jaincollege-cs-1234
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  
  storageClassName: manual 
