apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: s-jaincollege-it-6080
spec:
  owner:
    kind: User
    name: s-jaincollege-it-6080
  resourceQuotaSpec:
    hard:
      cpu: "4"
      memory: "4Gi"
      requests.nvidia.com/gpu: "0"
      requests.nvidia.com/mig-3g.71gb: "1"
      requests.nvidia.com/mig-2g.35gb: "0"
      requests.nvidia.com/mig-1g.18gb: "0"
      requests.storage: "10Gi"
  
