apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ln-s-jainschool-primary-12345
  namespace: ln-s-jainschool-primary-12345
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  
  storageClassName: manual 
